### ISSUE TITLE
Add AI search to Pattern Module

### ISSUE THREAD

**Issue by vyta** [Azure/terraform-azurerm-avm-ptn-ai-reference-implementation#8]
Ensure this is configurable (ex; toggle on/off)

**Comment by seekerofsai** [comment]
working with Bilal on publishing the azure search resource avm module.  once it gets published a PR will be raised for pattern module with azure search resource

**Comment by soallam** [comment]
Working with Bilal on AVM team to publish Search research module. Dependency on AVM team
